set nocompatible
filetype plugin indent on
syntax enable

let mapleader = " "
let maplocalleader = " "

set number
set cursorline
set mouse=a
if has('clipboard')
  set clipboard=unnamedplus
endif
set hidden
set confirm
set updatetime=300
set timeoutlen=300
set wildmenu
set wildmode=longest:full,full
set completeopt=menuone,noinsert,noselect

set ignorecase
set smartcase
set incsearch
set hlsearch

set expandtab
set shiftwidth=2
set tabstop=2
set smartindent

set splitbelow
set splitright
set wrap
set linebreak
set breakindent
set scrolloff=8
set sidescrolloff=8

set undofile
set noswapfile
set nobackup
set nowritebackup

" VSCode-style shortcuts for the built-in Vim experience.
nnoremap <silent> <C-s> :write<CR>
inoremap <silent> <C-s> <Esc>:write<CR>a
vnoremap <silent> <C-s> <Esc>:write<CR>gv

nnoremap <silent> <C-b> :Lexplore<CR>
nnoremap <silent> <C-f> /
nnoremap <silent> <C-w> :bdelete<CR>
nnoremap <silent> <Tab> :bnext<CR>
nnoremap <silent> <S-Tab> :bprevious<CR>
nnoremap <silent> <leader>w :write<CR>
nnoremap <silent> <leader>q :quit<CR>
nnoremap <silent> <leader>h :nohlsearch<CR>
nnoremap <silent> <leader>e :Lexplore<CR>
nnoremap <silent> <leader>r :oldfiles<CR>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

vnoremap < <gv
vnoremap > >gv
vnoremap <A-j> :move '>+1<CR>gv=gv
vnoremap <A-k> :move '<-2<CR>gv=gv
nnoremap <A-j> :move .+1<CR>==
nnoremap <A-k> :move .-2<CR>==

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

augroup user_vscode_like_vim
  autocmd!
  if exists('##TextYankPost')
    autocmd TextYankPost * silent! call timer_start(120, {-> execute('silent! nohlsearch')})
  endif
  autocmd FileType help,qf,man nnoremap <silent> <buffer> q :close<CR>
augroup END
